#! /bin/sh

. ./scripts/common

version=$(get_schema_version)
galaxy_version="$1"

echo "Generating sphinx document for FOS $Gre$version$RCol"

srcs=`find -name 'fortios_*.py' |grep "./output/$version/"`

#1. copy the template to output directory
sphinxdoc_root="galaxy_output/$version/sphnix_document"
mkdir -p $sphinxdoc_root
rm -rf $sphinxdoc_root/* $sphinxdoc_root/.git
cp -R galaxy_templates/sphinx_document/*  $sphinxdoc_root/
mkdir -p $sphinxdoc_root/gen

#1.cond. substitutue some tags
sed -i "s={{__galaxy_version__}}=$galaxy_version=g" $sphinxdoc_root/index.rst

#2 copy all rst files to the target directory
for f in $srcs
do
    docfile=`echo $f |sed 's/\.py$/.rst/g'`
    cp $docfile $sphinxdoc_root/gen
done

files_to_move_upward='fortios_configuration_fact.rst fortios_monitor_fact.rst fortios_monitor_config.rst'
for f in $files_to_move_upward
do
    mv $sphinxdoc_root/gen/$f $sphinxdoc_root/
done

echo "generated sphinx documents: $Gre$sphinxdoc_root$RCol"
