#! /bin/sh

. ./scripts/common

echo $Gre"Steps to generate Galaxy collection and Sphinx document for FortiOS:"
echo "\t1). Download schema from the Fortigate device"
echo "\t2). Generate raw Ansible modules"
echo "\t3). Generate raw sphinx .rst documents"
echo "\t4). Generate Galaxy collection repository"
echo "\t5). Generate Sphinx document repository"
echo "$RCol"

ask_for_proceed() {
    printf $BYel"do you want to proceed? [yes/no]$RCol"
    read option
    if [ "$option" != "yes" ]; then
	    exit 1
    fi
}

ask_for_proceed

#1: download the schema to fgt_schema.json
./scripts/download_fgt_schema.sh

#2
python2 ./scripts/generate_modules.py


#3
sh scripts/generate_doc

#4: the galaxy version argument $1
sh scripts/generate_collection  $1


#5
sh scripts/generate_sphinx_doc

